apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      containers:
        - name: todo-api
          image: ghcr.io/tejas115/todo-api:3119fbb1e37ddf26dab9faee2da71879f18aa210
          ports:
            - containerPort: 80
